# Copyright (c) 2018, IBM
# Copyright 2012-2015 Docker, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# Based on the opencontainers/runc .travis.yml file.

dist: xenial
sudo: required
language: c
cache: ccache

compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev libseccomp-dev bats genisoimage sudo iproute2 wget -y
  - sudo apt-get install --only-upgrade binutils gcc -y
  - export CC=gcc-6
  - export CXX=g++-6
  - git submodule update --init --recursive
  - bash travis_wait.sh 60 make -j16 --quiet world

script:
  - export CC=gcc-6
  - export CXX=g++-6
  - make integration
